trigger:
- none

pool:
     vmImage: ubuntu-latest
stages:
-  stage: DEMO
   jobs:
        - job: DEMO
           steps:
           - script: mvn clean
                    mvn install
                    mvn test


